version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: linux
    steps:
        - checkout
        - run:
            name: sample_command
            command: |
              echo "testing command on circle ci"